[package]
name = "aip-transport-http"
version.workspace = true
publish = false
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true

[dependencies]
aip-core.workspace = true
aip-transport.workspace = true
bytes.workspace = true
http.workspace = true
serde_json.workspace = true

[lints]
workspace = true
