[package]
name = "aip-transport-websocket"
version.workspace = true
publish = false
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true

[dependencies]
aip-core.workspace = true
aip-transport.workspace = true
async-trait.workspace = true
serde_json.workspace = true
tokio.workspace = true

[lints]
workspace = true
