[package]
name = "aip-transport-nats"
version.workspace = true
publish = false
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true

[dependencies]
aip-core.workspace = true
aip-transport.workspace = true
async-nats.workspace = true
async-trait.workspace = true
futures-util.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
tokio.workspace = true

[lints]
workspace = true
