[package]
name = "xtask"
version.workspace = true
publish = false
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true

[dependencies]
base64.workspace = true
clap.workspace = true
ed25519-dalek.workspace = true
flate2.workspace = true
getaip-distribution.workspace = true
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tar.workspace = true
tempfile.workspace = true
url.workspace = true

[lints]
workspace = true
